@startuml
interface Person{}

class Collaborator{}
Collaborator -.|> Person
Friend -.|> Person

class TrackNGOApplication{}

TrackNGOApplication --> Organization
TrackNGOApplication --> Donation



class Transaction{}
TrackNGOApplication --> Transaction


enum TransactionStatus{
PROCESSING
    DENIED
    ACCEPTED
}

Transaction --> TransactionStatus

enum TransactionType {
PURCHASE
    SALE
    RECEIPT
    PAYMENT
    DEBT
}

Transaction --> TransactionType




class Event{}
TrackNGOApplication --> Event

abstract class AbstractPerson{}
TrackNGOApplication --> AbstractPerson

AbstractPerson--> Person


enum DonationRecurrency{
ONE_TIME
    WEEKLY
    FORTNIGHT
    MONTHLY
    BIMONTHLY
    TRIMONTHLY
    SEASONAL
    SEMIANNUALLY
    ANNUALLY
    BIENNIALLY
    NOT_APPLICABLE
}
enum DonationStatus{
PENDING
    NOT_APPLICABLE
    ACTIVE
    INACTIVE
    SUSPENDED
}
enum DonationType{
MONETARY
    MATERIAL_GOODS
    PERISHABLE_FOOD
    NON_PERISHABLE_FOOD
}

Donation --> DonationRecurrency
Donation --> DonationStatus
Donation --> DonationType


enum EventType{
CHARITY
    FESTIVE
    INTERNAL

}

Event --> EventType


enum Profile{
SYSADMIN
    VOLUNTEER
    NOT_APPLICABLE
}

Person --> Profile

@enduml