@startuml
interface Friend{}
interface Beneficiary{}
interface User{}

class App{}

App --> User
App --> Beneficiary
App --> Friend

interface Authenticator{}
App --> Authenticator



class Transaction{}
App --> Transaction
Transaction --> Payment
Transaction --> Purchase

interface TransactionMethod{}

class Payment{}
Payment --> TransactionMethod
class PaymentValidator{}
Payment --> PaymentValidator

class Purchase{}
class PurchaseValidator{}
Purchase --> PurchaseValidator
Purchase --> TransactionMethod



class Finance{}
App --> Finance


class Event{}
App --> Event

@enduml
