@startuml
interface Authenticator{}
class BeneficiaryAuthenticator{}
BeneficiaryAuthenticator ..|> Authenticator
class AddressAuthenticator{}
AddressAuthenticator ..|> Authenticator
class IdentityAuthenticator{}
IdentityAuthenticator ..|> Authenticator
@enduml