@startuml
interface Friend{}
interface Beneficiary{}
interface User{}


class Collaborator{}
Collaborator ..|> Friend
class EconomicDonor{}
EconomicDonor ..|> Friend
class MaterialDonor{}
MaterialDonor ..|> Friend

class School{}
School ..|> Beneficiary
class Hospital{}
Hospital ..|> Beneficiary
class Geriatric{}
Geriatric ..|> Beneficiary
class Cooperative{}
Cooperative ..|> Beneficiary

class Operator{}
Operator ..|> User
class Volunteer{}
Volunteer ..|> User
@enduml