@startuml
class Donation{}

enum Period{
OneTime
Weekly
Quarterly
Monthly
Annually
}

enum Type{
Monetary
MaterialGoods
AlimentaryPerishable
AlimentaryNonePerishable
}


Donation --> Period
Donation --> Type

class Finance{}
class Debt{}

Finance --> Debt
Finance --> Donation
@enduml
